# Imagen base con Java
FROM eclipse-temurin:21-jre-jammy

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el jar al contenedor
COPY target/uptc-0.0.1-SNAPSHOT.jar app.jar

# Exponer puerto (Spring Boot usa 8080 por defecto)
EXPOSE 8080

# Variable de entorno opcional
ENV SERVER_ID=docker-instance

# Comando para ejecutar la app
ENTRYPOINT ["java", "-jar", "app.jar"]