# ---------- Etapa de build ----------
FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /app

# Copiar el código local en lugar de clonar
COPY . .

# Compilar y empaquetar (sin tests)
RUN mvn clean package -DskipTests

# ---------- Etapa final ----------
FROM eclipse-temurin:21-jre-jammy

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]