# ---------- Etapa de build ----------
FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /app

RUN apt-get update && apt-get install -y git

ENV GITHUB_TOKEN=$valor

# Copiar archivos del proyecto
COPY pom.xml .

COPY src ./src

# Compilar proyecto
RUN mvn clean package -DskipTests

# ---------- Etapa final ----------
FROM eclipse-temurin:21-jre-jammy

WORKDIR /app

# Copiar el JAR desde la etapa de build
COPY --from=build /app/target/*.jar app.jar

# Exponer puerto
EXPOSE 8080

# Variable de entorno
ENV SERVER_ID=docker-instance

# Ejecutar aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]