spring.application.name=uptc

# use in spring JPA to get into the data base
spring.datasource.url = ${DB_URL}
spring.datasource.username = ${DB_USER_NAME}
spring.datasource.password = ${DB_PASSWORD}

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.web.error.include-message=always

server.port=8080

# colors in the terminal
spring.output.ansi.enabled=ALWAYS
